### PR TITLE
Improve heatmap profiler performance 3x

### PR DESCRIPTION
**Pull request by jonashaag**
This brought down a 60s-to-profile program down to 20s for me.

### CODE REVIEW

**Comment by nvdv** [comment]
Hi,
thanks for PR!
It's nice fix, but it seems that call to `os.path.abspath`  is not necessary here and can be done in postprocessing phase (e.g. `fill_heatmap`) improving overall performance even more.

**Comment by nvdv** [comment]
@jonashaag Would you mind to change few lines I mentioned? I will merge this PR as soon as possible then.

**Comment by jonashaag** [comment]
Sorry not using vprof anymore so tbh not interested in working on this atm

**Comment by nvdv** [comment]
Ok, thanks!

**Pull request closed without merging**
