### PR TITLE
Don't suppress ImportErrors.

### PR DESCRIPTION
**Pull request by ryneeverett**
This is a tool for python programmers. We know what import errors are
and they give us some idea what we're doing wrong. Replacing them with a
vague error message doesn't help.

### CODE REVIEW

**Comment by nvdv** [comment]
Thanks for bringing this up.
Would you mind removing exception handling at `__main__.py` line 89, since nothing throws this kind of exceptions?
Thanks!

**Comment by ryneeverett** [comment]
@nvdv I don't understand the line you referenced, but I removed the unused exceptions.

**Comment by nvdv** [comment]
`except base_profile.ProfilerRuntimeException...` is there to catch all exceptions that are children of `ProfilerRuntimeException`. Since these exceptions are not raised anymore, this `except` is not necesary

**Comment by ryneeverett** [comment]
Gotcha. Just amended the commit.

**Comment by nvdv** [comment]
Looks great! Thanks!

**Pull request merged**
